### PR TITLE
Implemented the backend components of the nutrition goals system

### LINKED ISSUE #22: Create the means to store nutrition goals in the database
- Requires that these goals be persisted in the database
- Don't necessarily need to make these viewable or editable at this time

### PR DESCRIPTION
**Pull request by Eyerusalem-coder**
Closed #22

### CODE REVIEW

**Comment by MitchellTFord** [comment]
Did you actually create a page for nutrition goals? I don't see it anywhere.

As well, please try to give your commits more descriptive names in the future.

**Comment by Eyerusalem-coder** [comment]
I was trying to say just implemented a class. Sure I will

**Comment by MitchellTFord** [comment]
One other thing that I forgot about earlier: you should add an `insert`, an `update` and a `delete` method for `NutritionGoal` objects to `FTViewModel`

**Comment by Eyerusalem-coder** [comment]
Okay, I will do that. So those methods side be in the NutritionGoal class
right?

**Review by MitchellTFord — APPROVED** [review]
You can merge this now if you want, or you can add those methods to `FTViewModel` and merge it then.

**Comment by MitchellTFord** [comment]
No, they'll be in `FTViewModel`

**Pull request merged**
